
COMMISSION = .05
BUYING_MARGIN_THRESHOLD = .005
SELLING_MARGIN_THRESHOLD = .01
HOLD_PERCENT = .5

DEFAULT_DYNAMIC_STOP_LOSS = True
DEFAULT_DYNAMIC_TAKE_PROFIT = False
DEFAULT_PERCENT_STOP_LOST = .3
DEFAULT_PERCENT_TAKE_PROFIT = 3
